name: Run Tests

on:
  pull_request:
  push:
    branches:
      - main
      - release/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  test_cuda132_h100:
    name: test-cuda13.2-py${{ matrix.python-version }}-h100
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.12"]
        include:
          - name: H100
            runs-on: mt-l-x86iamx-22-225-h100
            torch-spec: '--pre torch --index-url https://download.pytorch.org/whl/nightly/cu132'
            gpu-arch-type: "cuda"
            gpu-arch-version: "13.2"
    permissions:
      id-token: write
      contents: read
    uses: pytorch/test-infra/.github/workflows/linux_job_v3.yml@main
    with:
      timeout: 60
      runner: ${{ matrix.runs-on }}
      gpu-arch-type: ${{ matrix.gpu-arch-type }}
      gpu-arch-version: ${{ matrix.gpu-arch-version }}
      submodules: recursive
      script: |
        python -m pip install --user --upgrade uv
        export PATH="$HOME/.local/bin:$PATH"
        uv python install ${{ matrix.python-version }}
        uv venv --python ${{ matrix.python-version }}
        export VIRTUAL_ENV="$PWD/.venv"
        export PATH="$VIRTUAL_ENV/bin:$PATH"
        PIP_EXTRA_INDEX_URL= UV_EXTRA_INDEX_URL= uv pip install ${{ matrix.torch-spec }}
        uv pip install '.[tests]'
        uv run --no-sync pytest test
